name: Escaneo Diario de Invictos

on:
  workflow_dispatch: # Esto activa el botón de "Play" manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          pip install requests google-generativeai

      - name: Ejecutar Escáner
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python script_futbol.py
